- name: Directories are created
  file:
    path: "{{ item.dir }}"
    mode: 0777
    recurse: yes
    state: directory
  with_items: configs
  tags: [jenkins]

- name: Container is running
  docker:
    name: jenkins
    image: jenkins
    ports: 8080:8080
    volumes:
      - /data/jenkins:/var/jenkins_home
      - /vagrant/.vagrant/machines:/machines
  register: container_result
  tags: [jenkins]

- pause: seconds=45
  when: container_result|changed
  tags: [jenkins]

- name: Configurations are present
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dir }}/{{ item.file }}"
    mode: "{{ item.mode }}"
  with_items: configs
  register: configs_result
  tags: [jenkins]

- name: Plugins are installed
  shell: "curl -X POST \
    -d '<jenkins><install plugin=\"{{ item }}@latest\" /></jenkins>' \
    --header 'Content-Type: text/xml' \
    http://{{ facter_ipaddress_eth1 }}:8080/pluginManager/installNecessaryPlugins"
  args:
    creates: /data/jenkins/plugins/{{ item }}
  with_items: plugins
  register: plugins_result
  tags: [jenkins]

- wait_for:
    path: /data/jenkins/plugins/{{ item }}
  with_items: plugins
  tags: [jenkins]

# Workaround to fix the bug in restarting containers from Ansible 2

- name: Container is stopped
  docker:
    name: jenkins
    image: jenkins
    state: stopped
  when: configs_result|changed or plugins_result|changed
  tags: [jenkins]

- name: Container is running
  docker:
    name: jenkins
    image: jenkins
    ports: 8080:8080
    volumes:
      - /data/jenkins:/var/jenkins_home
      - /vagrant/.vagrant/machines:/machines
  when: configs_result|changed or plugins_result|changed
  tags: [jenkins]
